image: ddgg/php_2020:build_v1

pipelines:
  default:
    - step:
        caches:
          - composer
          - node
        services:
          - mysql
          - redis
        script:
          - while ! timeout 1 bash -c "echo > /dev/tcp/localhost/3306"; do echo "Waiting for MySQL..."; sleep 1; done
          - while ! timeout 1 bash -c "echo > /dev/tcp/localhost/6379"; do echo "Waiting for Redis..."; sleep 1; done
          - pushd 08_laravel/02_exercise/project/
          -   composer install
          -   cp .env.example .env
          -   php artisan key:generate
          -   php artisan serve --port 8888 &
          -   while ! timeout 1 bash -c "echo > /dev/tcp/localhost/8888"; do echo "Waiting for server..."; sleep 1; done
          -   vendor/bin/codecept run
          -   vendor/bin/codecept run --xml test_report.xml
          -   killall php
          - popd
          - .ci/collect_reports.sh
definitions:
  services:
    mysql:
      image: mysql:8.0
      variables:
        MYSQL_ROOT_PASSWORD: root123
        MYSQL_DATABASE: test
        MYSQL_USER: test
        MYSQL_PASSWORD: test123
    redis:
      image: redis
